// <auto-generated />
using Boticario.BelezaWeb.Infra.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace Boticario.BelezaWeb.Infra.Data.Migrations
{
	[DbContext(typeof(BelezaWebDbContext))]
	partial class BelezaWebDbContextModelSnapshot : ModelSnapshot
	{
		protected override void BuildModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
					.HasAnnotation("ProductVersion", "3.1.9");

			modelBuilder.Entity("Boticario.BelezaWeb.Domain.Entities.Inventory", b =>
					{
						b.Property<int>("Id")
											.ValueGeneratedOnAdd()
											.HasColumnType("INTEGER");

						b.Property<int>("ProductSku")
											.HasColumnType("INTEGER");

						b.HasKey("Id");

						b.HasIndex("ProductSku")
											.IsUnique();

						b.ToTable("Inventory");
					});

			modelBuilder.Entity("Boticario.BelezaWeb.Domain.Entities.Product", b =>
					{
						b.Property<int>("Sku")
											.ValueGeneratedOnAdd()
											.HasColumnType("INTEGER");

						b.Property<string>("Name")
											.IsRequired()
											.HasColumnType("TEXT")
											.HasMaxLength(500);

						b.HasKey("Sku");

						b.ToTable("Product");
					});

			modelBuilder.Entity("Boticario.BelezaWeb.Domain.Entities.Warehouse", b =>
					{
						b.Property<int>("Id")
											.ValueGeneratedOnAdd()
											.HasColumnType("INTEGER");

						b.Property<int>("InventoryId")
											.HasColumnType("INTEGER");

						b.Property<string>("Locality")
											.IsRequired()
											.HasColumnType("TEXT")
											.HasMaxLength(100);

						b.Property<int>("Quantity")
											.HasColumnType("INTEGER");

						b.Property<string>("Type")
											.IsRequired()
											.HasColumnType("TEXT")
											.HasMaxLength(50);

						b.HasKey("Id");

						b.HasIndex("InventoryId");

						b.ToTable("Warehouse");
					});

			modelBuilder.Entity("Boticario.BelezaWeb.Domain.Entities.Inventory", b =>
					{
						b.HasOne("Boticario.BelezaWeb.Domain.Entities.Product", "Product")
											.WithOne("Inventory")
											.HasForeignKey("Boticario.BelezaWeb.Domain.Entities.Inventory", "ProductSku")
											.OnDelete(DeleteBehavior.Cascade)
											.IsRequired();
					});

			modelBuilder.Entity("Boticario.BelezaWeb.Domain.Entities.Warehouse", b =>
					{
						b.HasOne("Boticario.BelezaWeb.Domain.Entities.Inventory", "Inventory")
											.WithMany("Warehouses")
											.HasForeignKey("InventoryId")
											.OnDelete(DeleteBehavior.Cascade)
											.IsRequired();
					});
#pragma warning restore 612, 618
		}
	}
}
