USE [master]
GO

/****** Object:  Database [Boticario]    Script Date: 5/18/2022 7:28:14 AM ******/
CREATE DATABASE [Boticario]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Boticario', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Boticario.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Boticario_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Boticario_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Boticario].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Boticario] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Boticario] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Boticario] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Boticario] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Boticario] SET ARITHABORT OFF 
GO

ALTER DATABASE [Boticario] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Boticario] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Boticario] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Boticario] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Boticario] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Boticario] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Boticario] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Boticario] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Boticario] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Boticario] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Boticario] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Boticario] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Boticario] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Boticario] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Boticario] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Boticario] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Boticario] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Boticario] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Boticario] SET  MULTI_USER 
GO

ALTER DATABASE [Boticario] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Boticario] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Boticario] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Boticario] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Boticario] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Boticario] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Boticario] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Boticario] SET  READ_WRITE 
GO


