//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WarehouseResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WarehouseResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Projeto.Domain.Resources.WarehouseResource", typeof(WarehouseResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha inesperada ao inserir warehouse na base..
        /// </summary>
        public static string DbCreateUnexpectedError {
            get {
                return ResourceManager.GetString("DbCreateUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro inesperado ao {0} o warehouse {1}..
        /// </summary>
        public static string ExceptionUnexpectedly {
            get {
                return ResourceManager.GetString("ExceptionUnexpectedly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamanho da Localização inválido..
        /// </summary>
        public static string LocalityMaximumLength {
            get {
                return ResourceManager.GetString("LocalityMaximumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localização é obrigatória..
        /// </summary>
        public static string LocalityRequired {
            get {
                return ResourceManager.GetString("LocalityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produto SKU é obrigatório..
        /// </summary>
        public static string ProdutoSkuRequired {
            get {
                return ResourceManager.GetString("ProdutoSkuRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produto Quantidade informada deve ser maior ou igual a zero..
        /// </summary>
        public static string QuantityNegative {
            get {
                return ResourceManager.GetString("QuantityNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamanho do Warehouse Tipo inválido..
        /// </summary>
        public static string TypeMaximumLength {
            get {
                return ResourceManager.GetString("TypeMaximumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse Tipo é obrigatório..
        /// </summary>
        public static string TypeRequired {
            get {
                return ResourceManager.GetString("TypeRequired", resourceCulture);
            }
        }
    }
}
