//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BelezaNaWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class produto
    {
        public int Id { get; set; }
        public int Id_inventory { get; set; }
        public string name { get; set; }
        public string sku { get; set; }
    
        public virtual inventory inventory { get; set; }
    }
}
