using Boticario.Core.Domains.Base;
using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Text;
using System.Threading.Tasks;

namespace Boticario.Core.Interfaces.Repositories.Base
{
    public interface IRepositoryBase<TEntity> where TEntity : EntityBase
    {
        Task<TEntity> Obter(int id);

        Task<TEntity> Obter(Expression<Func<TEntity, bool>> expressao);

        Task<List<TEntity>> Listar(Expression<Func<TEntity, bool>> expressao);

        Task<int> Contar(Expression<Func<TEntity, bool>> expressao);

        Task<bool> Existe(Expression<Func<TEntity, bool>> expressao);

        Task<IAutoGeneratedValue> Inserir(TEntity entity);

        Task Atualizar(TEntity entity);

        Task Deletar(int id);
    }

    public interface IAutoGeneratedValue
    {
        int Valor { get; }
    }
}
